"""Add JSON sources to Message

Revision ID: b19195ec6c99
Revises: 
Create Date: 2025-06-25 20:03:12.303387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19195ec6c99'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sources', sa.JSON(), nullable=True))
        batch_op.alter_column('conversation_id',
               existing_type=sa.CHAR(length=36),
               type_=sa.String(length=36),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=sa.String(length=36),
               type_=sa.CHAR(length=36),
               nullable=True)
        batch_op.drop_column('sources')

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.CHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
